In [1]:
import sys
import numpy as np
import matplotlib as plt

In [61]:
#Inputs
X = np.array([[1.0, 2.0, 3.0, 2.5],
             [2.0, 5.0, -1.0, 2.0],
             [-1.5, 2.7, 3.3, -0.8]])

#Creating hidden layers
class Layer_Dense:
    #Initialize using the number of inputs and neurons
    def __init__(self, n_inputs, n_neurons):
        #Create an array of size (n_inputs x n_neurons) that are random based on the normal distrution
        #scaled by a tenth
        self.w = 0.1 * np.random.randn(n_inputs, n_neurons)
        #Create a row vector based on the number of neurons
        self.bias = np.zeros([1, n_neurons])
    #Method to compute the output, takes in an input matrix
    def forward(self, inputs):
        self.output = inputs@self.w + self.bias
#Create the first hidden layer with 5 inputs and 4 neurons
layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)

layer1.forward(X)
print("Layer 1: \n")
print(layer1.output)

print("---------------------------")
print("Layer 2: \n")
layer2.forward(layer1.output)
print(layer2.output)

Layer 1: 

[[ 0.0683875   0.55235072  0.31697624  0.1703925  -0.62046403]
 [ 0.48320411  0.86106744  0.72535015  1.2629097  -0.01888736]
 [ 0.06367211  0.02129266  0.82709157 -0.55830642 -0.6831859 ]]
---------------------------
Layer 2: 

[[ 0.01954635 -0.03031127]
 [-0.14431958 -0.06097116]
 [-0.08686092  0.07381831]]
